import os, sys
ROOT = os.path.dirname(os.path.abspath(sys.modules['__main__'].__file__))
ASSETS = os.path.join(ROOT, "assets")
IMAGE_SPRITES = os.path.join(ASSETS, "sprites/images")
FONTS = os.path.join(ASSETS, "fonts")
ICONS = os.path.join(ASSETS, "icons")

FONT = os.path.join(FONTS, "fixed_sys.ttf")
FONT2 = os.path.join(FONTS, "unifont.otf")

# BASE VISUAL
MIDDLE = (960, 540)
CARD_HEIGHT = 128
CARD_WIDTH = 82


# NETWORK
DEFAULT_IP = 'localhost'
DEFAULT_PORT = 54322

# DESIGN
RGB_COLORS = [(237, 28, 36), (80, 170, 68), (0, 114, 188), (255, 222, 22)]
COLORS = ["red", "green", "blue", "yellow"]
SPECIAL_COLOR = "black"

# CARDS
VALUES = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "switch", "skip", "plus2", "colors", "plus4"]
SPECIAL_VALUES = ["colors", "plus4"]

# RULES
ACTIONS_PER_TURN = 1
START_CARDS_AMOUNT = 7
MAX_TURN_LENGTH = 30 # in seconds
PENALTY_CARD_AMOUNT = 2

# STACKS VISUALS
MAX_STACKS = 3
BASE_STACK_SIZE = 2.5
BASE_STACK_ANGLE = 3
STACK_ANGLE_DIFFERENCE = -6
BASE_STACK_POSITION = (MIDDLE[0], MIDDLE[1] - 115)
BASE_STACK_CARD_DISTANCE = (-0.3, -2.25)
STACK_DISTANCE = (-CARD_WIDTH*BASE_STACK_SIZE*1.5, 0)
STACK_SIZES = [BASE_STACK_SIZE]*MAX_STACKS
STACK_ANGLES = [BASE_STACK_ANGLE + STACK_ANGLE_DIFFERENCE*i for i in range(MAX_STACKS)]
STACK_POSITIONS = [(BASE_STACK_POSITION[0] + STACK_DISTANCE[0]*i, BASE_STACK_POSITION[1] + STACK_DISTANCE[1]*i) for i in range(MAX_STACKS)]
STACK_CARD_DISTANCES = [BASE_STACK_CARD_DISTANCE]*MAX_STACKS

# HANDS VISUALS
CARD_BACK_ASSET = "cardback"
CARD_BASE_WIDTH = 300
CARD_HOVER_OFFSET = (CARD_BASE_WIDTH/60, -CARD_BASE_WIDTH/2, 1.2, 1) # (posX, posY, scaleX, scaleY) 
HAND_BASE_HARD_WIDTH = 1
HAND_BASE_SOFT_WIDTH = 1/6
    # Own Hand
OWN_HAND_POSITION = (960-CARD_BASE_WIDTH/2, 750)
OWN_HAND_SIZE = 3
OWN_HAND_ANGLE = 0 # DEG
OWN_HAND_CARD_SPACING = 1
    # Other Players
OTHER_HANDS_POSITIONS = [(320-CARD_BASE_WIDTH/2, 250), (960-CARD_BASE_WIDTH/2, 0), (1600-CARD_BASE_WIDTH/2, 250)]
OTHER_HANDS_SIZES = (1.5, 2, 1.5)
OTHER_HANDS_ANGLES = (-45, 0, 45) # DEG
OTHER_HANDS_CARD_SPACING = 0.7
